<a href="https://colab.research.google.com/github/GuerreroG226/programacion1/blob/main/ClaseSemana12(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Escritura de archivos en Python

In [1]:
with open('archivo.txt', 'w') as f:
    f.write('Hola, este es un archivo de texto.\n')
    f.write('Este es el segundo renglón del archivo.\n')

"w" es para editar el objeto o arguemnto dado.

In [2]:
with open('archivo.txt', 'r') as f:
  print(f.read())

Hola, este es un archivo de texto.
Este es el segundo renglón del archivo.

aqui "r" es para otra funcion, por ejemplo, leerlo.

In [3]:
from google.colab import files
files.download("archivo.txt")

In [5]:
with open('archivo.txt', 'a') as f:
    f.write('\nEste es el tercer renglón del archivo.')

In [6]:
with open('archivo.txt', 'r') as f:
  print(f.read())

Hola, este es un archivo de texto.
Este es el segundo renglón del archivo.

Este es el tercer renglón del archivo.
Este es el tercer renglón del archivo.

In [7]:
with open('archivo.txt', 'r') as f:
    lines = f.readlines()

# Eliminar la última línea si el archivo no está vacío
if lines:
    lines = lines[:-1]

with open('archivo.txt', 'w') as f:
    f.writelines(lines)

Ahora, si leemos el archivo de nuevo, la última línea debería haber sido eliminada.

In [8]:
with open('archivo.txt', 'r') as f:
  print(f.read())

Hola, este es un archivo de texto.
Este es el segundo renglón del archivo.

Este es el tercer renglón del archivo.

In [10]:
from google.colab import files
uploaded = files.upload()

Saving archivo.txt to archivo (1).txt

In [11]:
with open('archivo (1).txt', "w") as f:
  f.write("Este archivo se modificó por completo.\n")
  f.write("linea 1.\n")
  f.write("linea 2.\n")

In [12]:
with open('archivo (1).txt', 'r') as f:
  print(f.read())

Este archivo se modificó por completo.
linea 1.
linea 2.

In [13]:
from google.colab import files
files.download("archivo (1).txt")

Archivos csv

In [15]:
import csv

datos = [
    ["Nombre", "Edad", "Ciudad"],
    ["Juan", 25, "Madrid"],
    ["María", 30, "Barcelona"],
    ["Jose", 36, "Santa Maria"]
]

with open("datos.csv", "w", newline="") as f:
    writer = csv.writer(f)  #writer no es una funcion integrada pues la necesitamos del modulo csv
    writer.writerows(datos)

In [16]:
with open("datos.csv", "r") as f:
  print(f.read())

Nombre,Edad,Ciudad
Juan,25,Madrid
María,30,Barcelona
Jose,36,Santa Maria

In [17]:
files.download("datos.csv")

In [18]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [19]:
ruta = "/content/drive/MyDrive/datos.csv"

import shutil
shutil.copy("datos.csv", ruta)

'/content/drive/MyDrive/datos.csv'

In [20]:
with open(ruta, "r") as f:
  print(f.read())

Nombre,Edad,Ciudad
Juan,25,Madrid
María,30,Barcelona
Jose,36,Santa Maria

In [27]:
with open(ruta, "r") as f:
  data = list(csv.reader(f))

  data.append(["Diego", 29, "Cevallos"])

data

[['Nombre', 'Edad', 'Ciudad'],
 ['Juan', '25', 'Madrid'],
 ['María', '30', 'Barcelona'],
 ['Jose', '36', 'Santa Maria'],
 ['Diego', 29, 'Cevallos']]

In [23]:
import pandas as pd
data1 = pd.DataFrame(data)
data1

        0     1            2
0  Nombre  Edad       Ciudad
1    Juan    25       Madrid
2   María    30    Barcelona
3    Jose    36  Santa Maria
4   Diego    29     Cevallos

In [29]:
import csv

ruta = "/content/drive/MyDrive/datos.csv"

# Leer
with open(ruta, "r") as f:
    data = list(csv.reader(f))

# Mostrar antes
print("ANTES:")
print(data)

# Agregar fila
data.append(["Diego", "28", "Armenia"])

# Guardar
with open(ruta, "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(data)

# Mostrar después
print("\nDESPUÉS:")
with open(ruta, "r") as f:
    print(f.read())

ANTES:
[['Nombre', 'Edad', 'Ciudad'], ['Juan', '25', 'Madrid'], ['María', '30', 'Barcelona'], ['Jose', '36', 'Santa Maria']]

DESPUÉS:
Nombre,Edad,Ciudad
Juan,25,Madrid
María,30,Barcelona
Jose,36,Santa Maria
Diego,28,Armenia

In [38]:
paises = ["España", "España", "España", "España"]

In [36]:
import pandas as pd
df = pd.read_csv(ruta)
df

  Nombre  Edad       Ciudad
0   Juan    25       Madrid
1  María    30    Barcelona
2   Jose    36  Santa Maria
3  Diego    28      Armenia

In [37]:
df["Nueva_columna"] = "valor"
df["Nueva_columna"] = [10, 20, 30, None]
df

  Nombre  Edad       Ciudad  Nueva_columna
0   Juan    25       Madrid           10.0
1  María    30    Barcelona           20.0
2   Jose    36  Santa Maria           30.0
3  Diego    28      Armenia            NaN

In [35]:
import os
os.listdir("/content/drive/MyDrive")

['Colab Notebooks',
 'LA PENA DE MUERTE.gdoc',
 'Saber leer_INSTITUTO CERVANTES.pdf',
 '1. (1).txt',
 '1..txt',
 '1774580674393.jpg',
 '1774580674397.jpg',
 '1774580674400.jpg',
 '1774584675110.jpg',
 '1774584675117.jpg',
 'datos.csv']