<a href="https://colab.research.google.com/github/GuerreroG226/programacion1/blob/main/Segunda_evaluacion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Nombre** : Gustavo Andrés Guerrero Medina

#**Código** : 2260669

# **PARTE PRÁCTICA**

INSTRUCCIÓN #1:

definición

In [ ]:
XY = "10857958765"
Z = "34"

In [ ]:
print(XY[-2:11])
print(Z[-1])

65
4

código

In [ ]:
import numpy as np

np.random.seed(0)

datos = np.random.randint(1 * int(XY[-2:11]), 19 * int(Z[-1]), 50)

escala

In [ ]:
x_bar = np.mean(datos)
S_x = np.std(datos)

scale_function = lambda x: (x - x_bar) / S_x

datos_escalados = np.array([scale_function(x) for x in datos])

print("Datos originales:", datos)
print("Media:", x_bar)
print("Desviación estándar:", S_x)
print("Datos escalados:", datos_escalados)

Datos originales: [70 65 68 68 72 74 68 70 67 69 72 71 73 73 75 66 71 72 72 73 66 70 74 73
 74 69 68 65 68 70 65 67 68 73 66 68 68 68 72 65 66 74 74 65 75 69 72 68
 67 72]
Media: 69.76
Desviación estándar: 3.036840463376369
Datos escalados: [ 0.07902951 -1.56741853 -0.57954971 -0.57954971  0.73760872  1.39618793
 -0.57954971  0.07902951 -0.90883931 -0.2502601   0.73760872  0.40831911
  1.06689832  1.06689832  1.72547754 -1.23812892  0.40831911  0.73760872
  0.73760872  1.06689832 -1.23812892  0.07902951  1.39618793  1.06689832
  1.39618793 -0.2502601  -0.57954971 -1.56741853 -0.57954971  0.07902951
 -1.56741853 -0.90883931 -0.57954971  1.06689832 -1.23812892 -0.57954971
 -0.57954971 -0.57954971  0.73760872 -1.56741853 -1.23812892  1.39618793
  1.39618793 -1.56741853  1.72547754 -0.2502601   0.73760872 -0.57954971
 -0.90883931  0.73760872]

descripción y DataFrame

In [ ]:
import pandas as pd

df = pd.DataFrame({'Datos Originales': datos, 'Datos Escalados': datos_escalados})
df

    Datos Originales  Datos Escalados
0                 70         0.079030
1                 65        -1.567419
2                 68        -0.579550
3                 68        -0.579550
4                 72         0.737609
5                 74         1.396188
6                 68        -0.579550
7                 70         0.079030
8                 67        -0.908839
9                 69        -0.250260
10                72         0.737609
11                71         0.408319
12                73         1.066898
13                73         1.066898
14                75         1.725478
15                66        -1.238129
16                71         0.408319
17                72         0.737609
18                72         0.737609
19                73         1.066898
20                66        -1.238129
21                70         0.079030
22                74         1.396188
23                73         1.066898
24                74         1.396188
25                69        -0.250260
26                68        -0.579550
27                65        -1.567419
28                68        -0.579550
29                70         0.079030
30                65        -1.567419
31                67        -0.908839
32                68        -0.579550
33                73         1.066898
34                66        -1.238129
35                68        -0.579550
36                68        -0.579550
37                68        -0.579550
38                72         0.737609
39                65        -1.567419
40                66        -1.238129
41                74         1.396188
42                74         1.396188
43                65        -1.567419
44                75         1.725478
45                69        -0.250260
46                72         0.737609
47                68        -0.579550
48                67        -0.908839
49                72         0.737609

In [ ]:
import pandas as pd

df = pd.DataFrame({'Datos Originales': datos, 'Datos Escalados': datos_escalados})
df.describe()

       Datos Originales  Datos Escalados
count         50.000000     5.000000e+01
mean          69.760000    -1.663114e-15
std            3.067672     1.010153e+00
min           65.000000    -1.567419e+00
25%           68.000000    -5.795497e-01
50%           69.500000    -8.561530e-02
75%           72.000000     7.376087e-01
max           75.000000     1.725478e+00

In [ ]:
dt = pd.DataFrame(datos)
dt.describe()

               0
count  50.000000
mean   69.760000
std     3.067672
min    65.000000
25%    68.000000
50%    69.500000
75%    72.000000
max    75.000000

exportar

In [ ]:
dt.to_csv('resultados.csv', index=False)

In [ ]:
from google.colab import files
files.download('resultados.csv')

SEGUNDA INSTRUCCIÓN

creación de DataFrame

In [ ]:
import pandas as pd
pda = pd.DataFrame({
    "Nombre": ["Juan", "María", "Pedro", "Ana", "Luis"],
    "Edad": [25, 30, 35, 40, 45],
    "Ciudad": ["Madrid", "Barcelona", "Valencia", "Sevilla", "Zaragoza"],
    "Altura": [1.75, 1.68, 1.72, 1.65, 1.7]
})

pda

  Nombre  Edad     Ciudad  Altura
0   Juan    25     Madrid    1.75
1  María    30  Barcelona    1.68
2  Pedro    35   Valencia    1.72
3    Ana    40    Sevilla    1.65
4   Luis    45   Zaragoza    1.70

selección de fila

In [ ]:
pda.head(2)

  Nombre  Edad     Ciudad  Altura
0   Juan    25     Madrid    1.75
1  María    30  Barcelona    1.68

selección de columnas

In [ ]:
pda['Nombre']

0     Juan
1    María
2    Pedro
3      Ana
4     Luis
Name: Nombre, dtype: object

selección de columnas especificas

In [ ]:
pda[['Edad', 'Altura']]

   Edad  Altura
0    25    1.75
1    30    1.68
2    35    1.72
3    40    1.65
4    45    1.70

añadir una nueva columna, donde la variable se transforme

In [ ]:
pda["Razon Peso-ALtura"] = pda["Altura"] / pda["Edad"]
pda

  Nombre  Edad     Ciudad  Altura  Razon Peso-ALtura
0   Juan    25     Madrid    1.75           0.070000
1  María    30  Barcelona    1.68           0.056000
2  Pedro    35   Valencia    1.72           0.049143
3    Ana    40    Sevilla    1.65           0.041250
4   Luis    45   Zaragoza    1.70           0.037778

agrupacion de variables:
menciona el promedio de edad por ciudad provista

In [ ]:
pda.groupby("Ciudad")["Edad"].mean()

Ciudad
Barcelona    30.0
Madrid       25.0
Sevilla      40.0
Valencia     35.0
Zaragoza     45.0
Name: Edad, dtype: float64

exportar archivo

In [ ]:
pda.to_csv('datos_procesados.csv', index=False)

In [ ]:
from google.colab import files
files.download('datos_procesados.csv')

**PROYECTO**

In [ ]:
W = '18'

In [ ]:
print(W[-1])

8

**PRUEBA A**

In [ ]:
import numpy as np
import pandas as pd

np.random.seed(1)

datoss = np.random.normal(loc=7.2, scale=0.4, size= 5 * int(W[-1]))

fg = pd.DataFrame({'Datos': datoss})

fg

       Datos
0   7.849738
1   6.955297
2   6.988731
3   6.770813
4   7.546163
5   6.279385
6   7.897925
7   6.895517
8   7.327616
9   7.100252
10  7.784843
11  6.375944
12  7.071033
13  7.046378
14  7.653508
15  6.760043
16  7.131029
17  6.848857
18  7.216885
19  7.433126
20  6.759752
21  7.657889
22  7.560636
23  7.400998
24  7.560342
25  6.926509
26  7.150844
27  6.825692
28  7.092845
29  7.412142
30  6.923336
31  7.041299
32  6.925131
33  6.861918
34  6.931502
35  7.194934
36  6.753076
37  7.293766
38  7.863921
39  7.496818

**PRUEBA B**

In [ ]:
np.random.seed(1)

datoss_gamma = np.random.gamma(shape=306, scale=0.0229, size=5 * int(W[-1]))

fg_gamma = pd.DataFrame({'Datos Gamma': datoss_gamma})

fg_gamma

    Datos Gamma
0      7.670451
1      6.757685
2      6.790426
3      6.578912
4      7.721830
5      6.699405
6      7.601618
7      6.206925
8      7.463575
9      6.568575
10     6.930959
11     6.654150
12     6.568296
13     7.468153
14     7.366671
15     6.729577
16     6.893060
17     7.214258
18     6.728233
19     6.666797
20     6.561893
21     7.094039
22     6.923242
23     6.650369
24     7.020128
25     6.747819
26     7.047985
27     7.249794
28     7.120634
29     6.859682
30     6.916465
31     7.237269
32     7.114730
33     7.360163
34     7.207142
35     6.881097
36     7.462680
37     7.626055
38     7.911770
39     6.455408

DataFrame

In [ ]:
am = pd.DataFrame({'Datos': datoss, 'Datos Gamma': datoss_gamma})
am

       Datos  Datos Gamma
0   7.849738     7.670451
1   6.955297     6.757685
2   6.988731     6.790426
3   6.770813     6.578912
4   7.546163     7.721830
5   6.279385     6.699405
6   7.897925     7.601618
7   6.895517     6.206925
8   7.327616     7.463575
9   7.100252     6.568575
10  7.784843     6.930959
11  6.375944     6.654150
12  7.071033     6.568296
13  7.046378     7.468153
14  7.653508     7.366671
15  6.760043     6.729577
16  7.131029     6.893060
17  6.848857     7.214258
18  7.216885     6.728233
19  7.433126     6.666797
20  6.759752     6.561893
21  7.657889     7.094039
22  7.560636     6.923242
23  7.400998     6.650369
24  7.560342     7.020128
25  6.926509     6.747819
26  7.150844     7.047985
27  6.825692     7.249794
28  7.092845     7.120634
29  7.412142     6.859682
30  6.923336     6.916465
31  7.041299     7.237269
32  6.925131     7.114730
33  6.861918     7.360163
34  6.931502     7.207142
35  7.194934     6.881097
36  6.753076     7.462680
37  7.293766     7.626055
38  7.863921     7.911770
39  7.496818     6.455408

In [ ]:
print(am['Datos Gamma'].describe())

print(am['Datos'].describe())

count    40.000000
mean      7.018198
std       0.398338
min       6.206925
25%       6.721026
50%       6.927100
75%       7.277387
max       7.911770
Name: Datos Gamma, dtype: float64
count    40.000000
mean      7.164161
std       0.390755
min       6.279385
25%       6.916381
50%       7.096548
75%       7.449049
max       7.897925
Name: Datos, dtype: float64

Analisis:

In [ ]:
print('Media               :', am['Datos'].mean())

print('Mediana             :', am['Datos'].median())

print('Minimo              :', am['Datos'].min())

print('Maximo              :', am['Datos'].max())

print('Desviación estándar :', am['Datos'].std())

print('Cuantil 25%         :', am['Datos'].quantile(0.25))

print('Cuantil 75%         :', am['Datos'].quantile(0.75))

Media               : 7.16416081017245
Mediana             : 7.096548308979315
Minimo              : 6.279384521247887
Maximo              : 7.897924705686592
Desviación estándar : 0.39075485201592997
Cuantil 25%         : 6.9163810843928974
Cuantil 75%         : 7.44904898017248

prueba de shapiro

In [ ]:
from scipy.stats import shapiro

In [ ]:
shapiro(am['Datos'])

ShapiroResult(statistic=np.float64(0.9679771107507844), pvalue=np.float64(0.30994284073303935))

In [ ]:
shapiro(am['Datos Gamma'])

ShapiroResult(statistic=np.float64(0.9723759177274889), pvalue=np.float64(0.42659308638818216))

Podemos ver que ambos Datos alcanzan un valor p mayor que 0.05.
entonces sí se puede admitir este valor como un 95% acertado respecto a la hipótesis del análisis.

**prueba t student**

In [ ]:
import numpy as np
import pandas as pd
import scipy.stats as stats

In [ ]:
t_rel, p_rel = stats.ttest_rel(am['Datos'], am['Datos Gamma'])
print("t-statistic:", t_rel)
print("p-value:", p_rel)

t-statistic: 2.171717912695844
p-value: 0.036021190046430465

El valor p es menor a 0.05, entonces afirmamos con un 95% de confianza que las medias no son iguales

**Kendall**

In [ ]:
t_sta, p_valu = stats.kendalltau(am['Datos'], am['Datos Gamma'])
print("t-statistic:", t_sta)
print("p-value:", p_valu)

t-statistic: 0.22820512820512823
p-value: 0.03809007124607287

podemos decir con 95% de confianza que ambas encuestas no estuvieron relacionadas, dado que el valor p es menor a 0.05

**Spearman**

In [ ]:
s_pea, p_value = stats.spearmanr(am['Datos'], am['Datos Gamma'])
print("t-statistic:", s_pea)
print("p-value:", p_value)

t-statistic: 0.34052532833020643
p-value: 0.03154742621481852

podemos decir con un 95% de confianza que los datos no estuvieron correlacionas dado que el valor p es menor a 0.05

**Modulos**

In [ ]:
import os
os.makedirs("comparacion", exist_ok=True)

In [ ]:
%%writefile comparacion/pruebat.py

import numpy as np
import pandas as pd
import scipy.stats as stats

def ttest_rel(data1, data2):
    t_rel, p_rel = stats.ttest_rel(data1, data2)
    print("t-statistic (prueba t Student):", t_rel)
    print("p-value (prueba t Student):", p_rel)

Writing comparacion/pruebat.py

In [ ]:
%%writefile comparacion/cor.py


import numpy as np
import pandas as pd
import scipy.stats as stats

def kendall(data1, data2):
    t_sta, p_valu = stats.kendalltau(data1, data2)
    print("t-statistic (Kendall):", t_sta)
    print("p-value (Kendall):", p_valu)


def spearman(data1, data2):
  t_sta, p_value = stats.spearmanr(data1, data2)
  print("t-statistic (Spearman):", t_sta)
  print("p-value (Spearman):", p_value)

Writing comparacion/cor.py

**DATOS DE APLICACION**

In [ ]:
df = pd.DataFrame({
 "Estudiante": range(1, 11),
 "Prueba_A": [7.1, 7.5, 6.8, 7.3, 7.0, 7.4, 6.9, 7.2, 7.6, 7.1],
 "Prueba_B": [6.9, 7.2, 7.0, 7.1, 6.8, 7.3, 7.0, 7.1, 7.4, 7.0]
})

df

   Estudiante  Prueba_A  Prueba_B
0           1       7.1       6.9
1           2       7.5       7.2
2           3       6.8       7.0
3           4       7.3       7.1
4           5       7.0       6.8
5           6       7.4       7.3
6           7       6.9       7.0
7           8       7.2       7.1
8           9       7.6       7.4
9          10       7.1       7.0

In [ ]:
from comparacion.pruebat import ttest_rel
ttest_rel(df['Prueba_A'], df['Prueba_B'])

t-statistic (prueba t Student): 2.282657730758047
p-value (prueba t Student): 0.04835186429465345

In [ ]:
from comparacion.cor import kendall, spearman
kendall(df['Prueba_A'], df['Prueba_B'])

t-statistic (Kendall): 0.7063224140220168
p-value (Kendall): 0.006046856693870933

In [ ]:
from comparacion.cor import spearman
spearman(df['Prueba_A'], df['Prueba_B'])

t-statistic (Spearman): 0.8395701571521512
p-value (Spearman): 0.002376639566080667